name:
  haha: hehe

server:
  port: 1888

ob:
  para1: hhh
  para2: 222
  para3: 222
spring:
  datasource:
    url: jdbc:mysql:///waterdatabase
    username: tianzhou
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: http://localhost:9000
  thymeleaf:
    cache: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'